### ISSUE TITLE
Data base

### ISSUE THREAD

**Issue by samvy** [YunoHost-Apps/kanboard_ynh#56] opened 2018-02-01 15:58 UTC
Dear contributors,

I am not sure if the following bug is a kanbord's bug or a kanboard_ynh's bug. Because I can not check it easily I post this issue here...

After installing with standard yunohost method I had this message (in debug mode) when i tried to change my projects settings :
> SQL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'predefined_email_subjects' in 'field list'
So I added the column 'predefined_email_subjects' in table 'projects' and now it works !

Regards (and sorry if I post in the wrong place)

**Comment by Jibec** [comment] 2018-02-01 16:21
weird indeed, thank you for sharing it, but if you can't reproduce it, I can't consider it a bug and try to fix it :(

I advise you to:

* make a backup,
* remove the column you added
* run the db:migrate script, as in https://github.com/YunoHost-Apps/kanboard_ynh/blob/master/scripts/upgrade#L142
* make sure the rights are still good: https://github.com/YunoHost-Apps/kanboard_ynh/blob/master/scripts/upgrade#L154:L156

Please let me know if it worked fine. I'm closing this bug but it doesn't mean we can't continue to discuss your specific issue.

**Closed by Jibec** 2018-02-01 16:21 UTC
