### ISSUE TITLE
Admin user

### ISSUE THREAD

**Issue by mentat-fr** [YunoHost-Apps/kanboard_ynh#29] opened 2016-03-06 08:16 UTC
Hello all
When I declare my user as admin, I didn't access KB admin interfaces.
So I cannot create a project, manage users, give rights to board ...
My only option is to create private KB like a normal user.

I check forum, documentation, github, issues ... Maybe I miss something ?
Thanks for your help.

**Comment by mbugeia** [comment] 2016-03-07 21:42
Hi,
You are right, it's a new bug. I need to fix this.

**Comment by mentat-fr** [comment] 2016-03-07 21:56
Thanks for the quickness !

**Comment by ruihildt** [comment] 2016-04-25 13:43
@mbugeia any news on this issue ? Kanboard is basically unusable for now.

**Comment by mbugeia** [comment] 2016-04-27 18:56
It should be fixed now, I removed the plugin, can you test it and give me a feedback ?
`sudo yunohost app upgrade -u https://github.com/YunoHost-Apps/kanboard_ynh kanboard`

**Comment by Vey** [comment] 2016-04-28 06:39
Hello @mbugeia, thanks a lot for your work !

I've been sneaking around for a while hoping to see this fixed and I'll need further usage to be sure but I'm glad to tell you it looks like it works ! \o/

But it did not using your command... :(

In order to get it working, i had to desinstall the app and do:

>sudo yunohost app install -u https://github.com/YunoHost-Apps/kanboard_ynh

I think the url used for the install through admin panel is using an old version and therefore upgrading is working but the admin issue is still occuring.

Anyway, it is working now and I cannot thank you enough for your work (and others helpers ;))!

App infos:
> Application version: 1.0.27
PHP version: 5.6.19-0+deb8u1
PHP SAPI: fpm-fcgi
OS version: Linux 3.14.32-xxxx-grs-ipv6-64
Database driver: mysql
Database version: 5.5.49-0+deb8u1

**Comment by mbugeia** [comment] 2016-04-28 07:26
Hi,
You're right, the admin panel is still using an old version of the package
so the bug is still here. That's because I wanted to verify that the fix
work before pushing the new version.

**Comment by ruihildt** [comment] 2016-04-29 08:24
Hi,

I can confirm uninstalling and installing make it work.

As for the one line command update it didn't work, actually the "-u" parameter is not recognized?

**Comment by mbugeia** [comment] 2016-04-29 12:03
@ruihildt thanks !
For installing the command is just sudo yunohost app install https://github.com/YunoHost-Apps/kanboard_ynh 
the last parameter can take a github url, a local directory or just the name of the application if it's an official app.

For upgrade -u is mandatory for an url (-f for a local directory)

More info with yunohost app install -h or yunohost app upgrade -h ;)

**Comment by bachy** [comment] 2016-07-22 10:05
i also had this issue, and i also had to remove the app and reinstall it since upgrade did not resolve the issue
it's been almost 2 month since the bug fixe, we should push it, shouldn't we ?

**Comment by mbugeia** [comment] 2016-07-23 15:11
PR is here: https://github.com/YunoHost/apps/pull/74

**Comment by Psycojoker** [comment] 2016-08-10 13:36
Issue migrated at https://dev.yunohost.org/issues/488

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)

**Closed by Psycojoker** 2016-08-10 13:36 UTC
Labels: bug
